name: Code tests Linux

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.ipynb'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.sh'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.ipynb'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.sh'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  uv-tests:
    name: Code tests (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (uv)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv and dependencies
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --dev --python=3.10  # tests for backwards compatibility
          uv pip install -r ch05/07_gpt_to_llama/tests/test-requirements-extra.txt
          uv add pytest-ruff nbval

      - name: Test Selected Python Scripts (uv)
        shell: bash
        run: |
          source .venv/bin/activate
          pytest --ruff setup/02_installing-python-libraries/tests.py
          pytest --ruff ch04/01_main-chapter-code/tests.py
          pytest --ruff ch05/01_main-chapter-code/tests.py
          pytest --ruff ch05/07_gpt_to_llama/tests/tests.py
          pytest --ruff ch06/01_main-chapter-code/tests.py

      - name: Validate Selected Jupyter Notebooks (uv)
        shell: bash
        run: |
          source .venv/bin/activate
          pytest --ruff --nbval ch02/01_main-chapter-code/dataloader.ipynb
          pytest --ruff --nbval ch03/01_main-chapter-code/multihead-attention.ipynb
          pytest --ruff --nbval ch02/04_bonus_dataloader-intuition/dataloader-intuition.ipynb

      - name: Test Selected Bonus Materials
        shell: bash
        run: |
          source .venv/bin/activate
          pytest ch02/05_bpe-from-scratch/tests/tests.py

      - name: Test Selected Bonus Materials
        shell: bash
        run: |
          source .venv/bin/activate
          uv pip install transformers
          pytest pkg/llms_from_scratch/tests/
